# This is a basic workflow to help you get started with Actions

name: Build the project with nex

on: [push]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build  
      - run: npm run build
